[package]
description = "ternary-hmm - SuperInstance ecosystem crate"
repository = "https://github.com/SuperInstance/ternary-hmm"
name = "ternary-hmm"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
ternary-types = { git = "https://github.com/SuperInstance/ternary-types.git", features = ["std"] }
